---
json_rpc_url: "https://api.mainnet-beta.solana.com/"
update_manifest_pubkey:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
current_update_manifest: ~
update_poll_secs: 3600
explicit_release:
  Semver: 1.9.4
releases_dir: /Users/lanceweisser/.local/share/solana/install/releases
active_release_dir: /Users/lanceweisser/.local/share/solana/install/active_release
